# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/zaldi/Desktop/geo_procc

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/zaldi/Desktop/geo_procc

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zaldi/Desktop/geo_procc/CMakeFiles /home/zaldi/Desktop/geo_procc/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zaldi/Desktop/geo_procc/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named geo_procc

# Build rule for target.
geo_procc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 geo_procc
.PHONY : geo_procc

# fast build rule for target.
geo_procc/fast:
	$(MAKE) -f CMakeFiles/geo_procc.dir/build.make CMakeFiles/geo_procc.dir/build
.PHONY : geo_procc/fast

cell.o: cell.cpp.o

.PHONY : cell.o

# target to build an object file
cell.cpp.o:
	$(MAKE) -f CMakeFiles/geo_procc.dir/build.make CMakeFiles/geo_procc.dir/cell.cpp.o
.PHONY : cell.cpp.o

cell.i: cell.cpp.i

.PHONY : cell.i

# target to preprocess a source file
cell.cpp.i:
	$(MAKE) -f CMakeFiles/geo_procc.dir/build.make CMakeFiles/geo_procc.dir/cell.cpp.i
.PHONY : cell.cpp.i

cell.s: cell.cpp.s

.PHONY : cell.s

# target to generate assembly for a file
cell.cpp.s:
	$(MAKE) -f CMakeFiles/geo_procc.dir/build.make CMakeFiles/geo_procc.dir/cell.cpp.s
.PHONY : cell.cpp.s

gdal_raster.o: gdal_raster.cpp.o

.PHONY : gdal_raster.o

# target to build an object file
gdal_raster.cpp.o:
	$(MAKE) -f CMakeFiles/geo_procc.dir/build.make CMakeFiles/geo_procc.dir/gdal_raster.cpp.o
.PHONY : gdal_raster.cpp.o

gdal_raster.i: gdal_raster.cpp.i

.PHONY : gdal_raster.i

# target to preprocess a source file
gdal_raster.cpp.i:
	$(MAKE) -f CMakeFiles/geo_procc.dir/build.make CMakeFiles/geo_procc.dir/gdal_raster.cpp.i
.PHONY : gdal_raster.cpp.i

gdal_raster.s: gdal_raster.cpp.s

.PHONY : gdal_raster.s

# target to generate assembly for a file
gdal_raster.cpp.s:
	$(MAKE) -f CMakeFiles/geo_procc.dir/build.make CMakeFiles/geo_procc.dir/gdal_raster.cpp.s
.PHONY : gdal_raster.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/geo_procc.dir/build.make CMakeFiles/geo_procc.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/geo_procc.dir/build.make CMakeFiles/geo_procc.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/geo_procc.dir/build.make CMakeFiles/geo_procc.dir/main.cpp.s
.PHONY : main.cpp.s

raster.o: raster.cpp.o

.PHONY : raster.o

# target to build an object file
raster.cpp.o:
	$(MAKE) -f CMakeFiles/geo_procc.dir/build.make CMakeFiles/geo_procc.dir/raster.cpp.o
.PHONY : raster.cpp.o

raster.i: raster.cpp.i

.PHONY : raster.i

# target to preprocess a source file
raster.cpp.i:
	$(MAKE) -f CMakeFiles/geo_procc.dir/build.make CMakeFiles/geo_procc.dir/raster.cpp.i
.PHONY : raster.cpp.i

raster.s: raster.cpp.s

.PHONY : raster.s

# target to generate assembly for a file
raster.cpp.s:
	$(MAKE) -f CMakeFiles/geo_procc.dir/build.make CMakeFiles/geo_procc.dir/raster.cpp.s
.PHONY : raster.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... geo_procc"
	@echo "... cell.o"
	@echo "... cell.i"
	@echo "... cell.s"
	@echo "... gdal_raster.o"
	@echo "... gdal_raster.i"
	@echo "... gdal_raster.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... raster.o"
	@echo "... raster.i"
	@echo "... raster.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

